docs: Add screencast recording script
intel/pmem-csi pull request #1056
Opened 2021-12-13 20:18 UTC by eadamsintel

This script will create an asciinema recording to show users
how to use the PMEM-CSI operator and drivers along with a
sample application deployed from the PMEM-CSI GitHub.

Signed-off-by: Eric Adams <eric.adams@intel.com>

2021-12-13 21:29 UTC, pohly requested changes
You should be able to merge all suggestions that you agree with via GitHub. Then locally, pull from your repo to get the changes.

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  Nothing is yet labeled for persistent memory.'
```suggestion
  out '#  Nothing is labeled yet for persistent memory.'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  Now install the PMEM-CSI operator. This can either be done by using the yaml files on'
```suggestion
  out '#  Now install the PMEM-CSI operator. This can be done either by using the yaml files on'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  the PMEM-CSI GitHub or by using the Operator Hub. If you are using OpenShift then the'
```suggestion
  out '#  the PMEM-CSI GitHub or by using the Operator Hub. If you are using OpenShift, then the'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  1) Create pmem-csi namespace if it does not exist.'
```suggestion
  out '#  1) Create the "pmem-csi" namespace if it does not exist.'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  Create a Persistent Volume Claim for that storage class.'
```suggestion
  out '#  Create a PersistentVolumeClaim for that StorageClass.'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  If you describe the PVC you will see the volume is still waiting for its first consumer.'
```suggestion
  out '#  If you describe the PVC, you will see the volume is still waiting for its first consumer.'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  Inside this pod there is an application called pmem-dax-check which can verify if'
Not sure about this one...

```suggestion
  out '#  Inside this pod there is an application called pmem-dax-check which can verify whether'
```

2021-12-13 21:29 UTC, pohly commented on docs/screencast-pmem.sh
> +  out '#  from a persistent memory volume.'
```suggestion
  out '#  MAP_SYNC is supported. If that works, then it confirms that the file is'
  out '#  stored on persistent memory.'
```

2021-12-13 22:23 UTC, pohly requested changes
Some short usage instruction at the top of the file would be useful. As it stands now, I have no clue what to do with it :sweat_smile:

2021-12-14 00:32 UTC, eadamsintel commented
I updated everything with your feedback and added instructions at the beginning on how to use. Ironically, I found after all the reviews "ouput" was spelled wrong.  I think I have everything correct now but if not can record another video.

2021-12-14 08:52 UTC, pohly approved these changes

2021-12-14 09:48 UTC, merged

2021-12-14 09:49 UTC, pohly commented
I'll update the link to the final animation separately and then backport that change to the versioned v1.0 documentation.

2021-12-14 09:50 UTC, pohly commented
https://asciinema.org/a/Bz0KrHGgwHMSokekheZazDR2m