Dev-manager canUse calc: fix operator order
intel/pmem-csi pull request #717
Opened 2020-08-28 08:15 UTC by okartau

Division as integer and then multiply, sheds off some value
from canUse size, and later when we align down by Align size,
we will lose whole alignment block because of that.
This creates issue where 1st run leaves one realAlign-sized block
unallocated, but 2nd start on same node will find it and create
a new relatively small namespace.

2020-08-28 09:08 UTC, pohly requested changes
Not strictly related, but can you use the opportunity to explain what "realalign" is? It's not obvious when reading this function.

The fix itself looks fine. Unit tests would be good, but we are already tracking that (issue #692 ).

2020-08-28 09:09 UTC, pohly commented
> Not strictly related, but can you use the opportunity to explain what "realalign" is?

And with that I meant "explain in the source code" - not here in the GitHub issue.

2020-08-28 11:13 UTC, okartau commented
testing failed but I believe it is not related to this change:

The Service "pmem-csi-scheduler" is invalid: spec.ports[0].nodePort: Invalid value: 32000: provided port is already allocated
[AfterEach] direct-testing-metrics

I will add another commit with asked "realalign" explanation.

2020-08-31 06:35 UTC, pohly approved these changes

2020-08-31 06:35 UTC, merged

2020-09-01 19:32 UTC, pohly commented
> The Service "pmem-csi-scheduler" is invalid: spec.ports[0].nodePort: Invalid value: 32000: provided port is already allocated
[AfterEach] direct-testing-metrics

I just hit the same locally. Seems to be timing issue with plenty of upstream issues that report it. I'll probably add a retry loop.