docs: introduction section for admins
intel/pmem-csi pull request #754
Opened 2020-09-29 15:39 UTC by pohly

We have most of the information documented already, but admins may
need some additional guidance on where to start and what's expected of
them. The new section also spells out some dos and don'ts.

Fixes #312

2020-09-29 15:40 UTC, pohly commented
@intelkevinputnam : can you perhaps help review this new documentation section (spelling, grammar, etc.)?

2020-09-29 16:39 UTC, avalluri commented on docs/install.md
> +  driver installation on that same node.
Would it make sense to mention about providing the different `StorageClasses` for those drivers?

2020-09-29 16:40 UTC, avalluri commented on docs/install.md
> +  driver installation on that same node.
Ignore this, I figured out that the next paragraph is having this.

2020-09-30 10:27 UTC, pohly commented
@avalluri so what do you think, is this complete enough? If we don't hear from @intelkevinputnam, shall we merge it?

2020-09-30 10:29 UTC, pohly commented
One thing that I noticed is that we don't have good documentation for storage class parameters. `eraseAfter` was only described once, in the context of inline volumes. Probably should be enhanced at some point.

2020-09-30 10:29 UTC, pohly commented
Upgrade/downgrade also may deserve a separate section.

2020-09-30 12:44 UTC, pohly commented
There is another issue open (https://github.com/intel/pmem-csi/issues/707) which gets (almost) addressed by this PR.

What was missing was this:
> operator in install.md must use the "pmem-csi.intel.com" name to be compatible with the example storage classes

I added another commit for that.

@avalluri: please have another look.

2020-09-30 13:11 UTC, avalluri commented
> @avalluri: please have another look.

Looks good.

2020-09-30 19:11 UTC, intelkevinputnam commented
@pohly I can take a look this afternoon.

2020-09-30 20:41 UTC, intelkevinputnam requested changes
Please consider these recommendations.

2020-09-30 20:41 UTC, intelkevinputnam commented on docs/install.md
> +This section summarizes the steps that may be needed during the entire
Line 23: replace "usage" with "life cycle".

2020-09-30 20:41 UTC, intelkevinputnam commented on docs/install.md
> +hardware on nodes and configure some or all of that PMEM for usage by
Line 28: possibly replace "that PMEM" with "those instances of PMEM"

2020-09-30 20:41 UTC, intelkevinputnam commented on docs/install.md
> +installation can only use either [direct device
Line 36: I'd recommend removing "either"

2020-09-30 20:41 UTC, intelkevinputnam commented on docs/install.md
> +The administrator must install PMEM-CSI, using either [the PMEM-CSI
Line 33: remove "either"

2020-09-30 20:41 UTC, intelkevinputnam commented on docs/install.md
> +PMEM-CSI twice on the same cluster with different modes, but then:
Line 39: recommend replacing "but then" with "with these restrictions"

2020-10-01 07:22 UTC, pohly commented
@intelkevinputnam : thanks, I've applied all of your suggestions.

2020-10-01 07:22 UTC, merged