Experimental: Overwrite with zero instead of random when shredding
intel/pmem-csi pull request #881
Opened 2021-02-04 19:30 UTC by okartau

shred default behavior is to write random data, but getting random data is slower than writing zeroes. In my small test with 8G file, I saw write with zeroes being almost twice faster than write with random. shred has option to add zero-fill at the end, but with setting number of random writes to zero, there will be only zero-write pass. 
I want to see how this affects overall test duration.
Also, we may discuss is fill with zeroes actually enough for real operation of the plugin, instead of even more secure fill-with-random style.

2021-02-05 13:11 UTC, okartau commented
This is not very good measurement as different PRs may bring various changes to timing, but timing list of recent jobs:
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/

indicate that job for this PR ran in almost 10% shorter time (5h5min) than other PRs close to it (5h30min):

2021-02-05 13:23 UTC, okartau commented
I propose we consider changing our erasing methods as in this PR.
The stronger "overwrite with random" method (based on what I have been seen documented) is meant to extra-assure data is even harder to recover from hard drives compared to data overwritten with static pattern. But this claim seems has roots with technology where the media (like hard disk surface) can be post-analyzed with special tools out-of-box. In our PMEM case, data is memory value (no surface), so does it matter at all do we overwrite it with zero or random? I think not, and thus we should select the faster method. Using random data is slower and consumes system random data pool. Proposal: lets shred with zeroes.

2021-02-05 13:57 UTC, avalluri commented
> Proposal: lets shred with zeroes.

I agree with this.

2021-02-08 08:07 UTC, pohly requested changes
Please update also the documentation.

2021-02-08 10:59 UTC, pohly requested changes
Please remove the "experimental" from the commit title.

2021-02-09 14:07 UTC, pohly approved these changes

2021-02-09 14:07 UTC, merged